language: python
sudo: required
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

addons:
  apt:
    packages:
      - libhdf5-serial-dev

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      pip install --upgrade virtualenv
      python -m virtualenv venv
      source venv/bin/activate
      export PATH=/usr/lib/ccache:$PATH
    else
      brew update
      brew install ccache hdf5
      export PATH=/usr/local/opt/ccache/libexec:$PATH
    fi
    mkdir -p $HOME/.config/yt
    echo "[yt]" > $HOME/.config/yt/ytrc
    echo "suppressStreamLogging = True" >> $HOME/.config/yt/ytrc
    cat $HOME/.config/yt/ytrc
    cp tests/matplotlibrc .

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    # install dependencies yt
    if [[ $TRAVIS_BUILD_STAGE_NAME != "Lint" ]]; then
      if [[ $MINIMAL == 1 ]]; then
        pip install -r tests/test_minimal_requirements.txt
      else
        pip install -r tests/test_requirements.txt
      fi
      pip install -e .
    else
      pip install -r tests/lint_requirements.txt
    fi

jobs:
  include:
    - stage: lint
      python: 3.6
      script: flake8 yt/

    - stage: lint
      python: 2.7
      script: flake8 yt/

    - stage: tests
      name: "Python: 2.7 Unit Tests"
      python: 2.7
      env: MINIMAL=1
      script: coverage run $(which nosetests) -c nose_unit.cfg

    - stage: tests
      name: "Python: 2.7 Unit Tests"
      python: 2.7
      script: coverage run $(which nosetests) -c nose_unit.cfg

    - stage: tests
      name: "Python: 3.5 Unit Tests"
      python: 3.5
      script: coverage run $(which nosetests) -c nose_unit.cfg

    - stage: tests
      name: "Python: 3.6 Unit Tests"
      python: 3.6
      script: coverage run $(which nosetests) -c nose_unit.cfg

    - stage: tests
      name: "Python: 2.7 Answer Tests"
      python: 2.7
      env: MINIMAL=1
      script: coverage run $(which nosetests) -c nose_answer.cfg
      after_failure: python tests/report_failed_answers.py -f -m --xunit-file "answer_nosetests.xml"

    - stage: tests
      name: "Python: 3.6 Answer Tests"
      python: 3.6
      script: coverage run $(which nosetests) -c nose_answer.cfg
      after_failure: python tests/report_failed_answers.py -f -m --xunit-file "answer_nosetests.xml"

    - stage: tests
      name: "MacOS: xcode7.3 Unit Tests"
      os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      cache:
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top
          - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
      script: nosetests -c nose_unit.cfg

after_success:
  - |
    if [[ $TRAVIS_BUILD_STAGE_NAME != "Lint" ]]; then
      codecov
    fi
